title: Dave Aasen's webpage
logo: /assets/img/string_net_crank.png
description: For personal use, posting files, links to favourite resources, etc.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
